name: coaching_ai
description: A new Flutter project.

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  chatwoot_sdk: ^0.0.9
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


