name: CoachingAI
description: A new Flutter project.

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  shared_preferences: ^2.2.2
  webview_flutter: ^4.2.2
  flutter_html: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
